# Supabase Configuration
# Reference: https://supabase.com/docs/reference/cli/config-toml

# A string used to distinguish different Supabase projects on the same host.
project_id = "anovzbbvasxsagkblbaf"

[api]
enabled = true
port = 54321

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323

[storage]
enabled = true
file_size_limit = "50MiB"
